### ISSUE TITLE
Packaging yubicommon and python-u2flib-server

### ISSUE THREAD

**Issue by FedericoCeratto** [Yubico/python-yubicommon#3]
Hello and thanks for developing these libraries.
To help package the libraries for Linux distributions, could you consider making a release of yubicommon on GitHub and PyPI?

This could enable removing the symlink in:
https://github.com/Yubico/python-u2flib-server/blob/master/u2flib_server/yubicommon

(just a nitpick: tag names are usually < version > or v< version > rather than < name >< version >)

Related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780099

Thank you!

**Comment by dainnilsson** [comment]
Hi, thank you for your interest in packaging python-u2flib-server.

The yubicommon project is in a state of rapid development, where API isn't yet at a stable point. Because if this it is important that users of the project, such as python-u2flib-server, are able to depend on specific states of the project, which is why the dependency is vendored into this repository. This doesn't really matter for the sake of packaging, as you should be basing the package off of the source tar.gz releases (such as https://github.com/Yubico/python-u2flib-server/releases/download/python-u2flib-server-3.2.0/python-u2flib-server-3.2.0.tar.gz) and not the contents of the repository itself. You'll see that it contains no symlinks.

As for tag names: If you can convince me that there would be some benefit to changing the scheme then I'll consider it. As far as I know there is no "best practice" when it comes to this. Semantic Versioning (which most of our projects follow) used to specify a tag naming scheme, but this was later dropped as it was determined that there was no reason to do so.

**Comment by reqa** [comment]
I've pushed my initial packaging status [here](https://github.com/reqa/pkg-python-u2flib-server)

**Comment by FedericoCeratto** [comment]
@dainnilsson I'm happy to announce that python-u2flib-server is now in Debian Unstable: https://tracker.debian.org/pkg/python-u2flib-server

I suppose this issue can be closed now, thanks for your inputs!

**Comment by dainnilsson** [comment]
Awesome, thanks!
